spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meetme
    username: wordbe
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  security:
    user:
      name: user
      password: 1234

  profiles:
    include: oauth

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
